version: '3'
services:
  product-service:
    image: product-service:1.0.0
    build: ./product-service
    ports:
      - 8125:8125
    command: mvn clean spring-boot:run
    depends_on:
      - mongo-db
  order-service:
    image: order-service:1.0.0
    build: ./order-service
    ports:
      - 8126:8126
    command: mvn clean spring-boot:run
    depends_on:
      - mongo-db
      - product-service

  mongo-db:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    expose:
      - 27017

