version: '3'
services:
  product-service:
    image: product-service:1.0.0
    build: ./product-service
    expose:
      - 8125
    command: mvn spring-boot:run
    environment:
      - TOKEN_CHECK_ENDPOINT=http://urp-service:8127/oauth/check_token
    depends_on:
      - mongo-db
  order-service:
    image: order-service:1.0.0
    build: ./order-service
    expose:
      - 8126
    command: mvn spring-boot:run
    environment:
      - PRODUCT_SERVICE_BASE_URL=http://product-service:8125/
      - TOKEN_CHECK_ENDPOINT=http://urp-service:8127/oauth/check_token
    depends_on:
      - mongo-db
      - product-service
  urp-service:
    image: urp-service:1.0.0
    build: ./urp-service
    ports:
      - 8127:8127
    command: mvn spring-boot:run
    depends_on:
      - mongo-db
  mongo-db:
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
  nginx:
    image: nginx:1.19.1
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8888:80
      - 9999:443
    depends_on:
      - urp-service
      - product-service
      - order-service