server:
  servlet:
    contextPath: /
  port: 8126

spring:
  data:
    mongodb:
      uri: mongodb://mongo-db:27017/SuperShopping?readPreference=primary&w=majority&journal=true&connectTimeoutMS=10000