server:
  servlet:
    contextPath: /
  port: 8125

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/SuperShopping?readPreference=primary&w=majority&journal=true&connectTimeoutMS=10000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
